In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data=pd.read_excel('Data_Train.xlsx')
test_data =pd.read_excel('Data_Test.xlsx')

In [3]:
train_data.shape,test_data.shape

((7628, 2), (2748, 1))

In [4]:
train_data.head()

STORY  SECTION
0  But the most painful was the huge reversal in ...        3
1  How formidable is the opposition alliance amon...        0
2  Most Asian currencies were trading lower today...        3
3  If you want to answer any question, click on ‘...        1
4  In global markets, gold prices edged up today ...        3

In [5]:
test_data.head()

STORY
0  2019 will see gadgets like gaming smartphones ...
1  It has also unleashed a wave of changes in the...
2  It can be confusing to pick the right smartpho...
3  The mobile application is integrated with a da...
4  We have rounded up some of the gadgets that sh...

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7628 entries, 0 to 7627
Data columns (total 2 columns):
STORY      7628 non-null object
SECTION    7628 non-null int64
dtypes: int64(1), object(1)
memory usage: 119.3+ KB


In [7]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2748 entries, 0 to 2747
Data columns (total 1 columns):
STORY    2748 non-null object
dtypes: object(1)
memory usage: 21.5+ KB


In [8]:
train_data.isnull().sum()

STORY      0
SECTION    0
dtype: int64

In [9]:
test_data.isnull().sum()

STORY    0
dtype: int64

In [10]:
train_data.describe()

SECTION
count  7628.000000
mean      1.357892
std       0.999341
min       0.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       3.000000

In [11]:
test_data.describe()

STORY
count                                                2748
unique                                               2737
top     This story has been published from a wire agen...
freq                                                    6

In [12]:
train_data['SECTION'].unique()

array([3, 0, 1, 2], dtype=int64)

In [13]:
train_data['SECTION'].value_counts()

1    2772
2    1924
0    1686
3    1246
Name: SECTION, dtype: int64

In [14]:
import re
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.tag import pos_tag
from nltk.corpus import stopwords
from nltk import chunk

In [15]:
lem = WordNetLemmatizer()
stop = stopwords.words('english')

In [16]:
train_new_data = []
for data in train_data['STORY']:
    data = data.lower()
    data = re.sub(r'[^a-z0-9]',' ',data)
    data = re.sub(r'\s+',' ',data)
    data = [lem.lemmatize(word) for word in data.split() if word not in stop]
    data = ' '.join(data)
    train_new_data.append(data)
    

In [17]:
train_new_data

['painful huge reversal fee income unheard among private sector lender essentially mean yes bank took granted fee structured loan deal paid accounted upfront book borrower turned defaulter fee tied loan deal fell crack gill vowed shift safer accounting practice amortizing fee income rather booking upfront gill move mend past way mean nasty surprise future good news considering investor love clean image loathe uncertainty gain without pain promise strong stable balance sheet come sacrifice well investor give hope phenomenal growth promise made kapoor',
 'formidable opposition alliance among congress jharkhand mukti morcha jmm jharkhand vikas morcha prajatantrik',
 'asian currency trading lower today south korean 0 4 china renminbi 0 23 china offshore 0 15 malaysian ringgit 0 12 indonesian rupiah 0 11 taiwan dollar 0 06 however japanese yen 0 32 dollar index measure u currency strength major currency trading 97 26 0 14 previous close 97 395',
 'want answer question click answer clicking 

In [18]:
test_new_data = []
for data in test_data['STORY']:
    data = data.lower()
    data = re.sub(r'[^a-z0-9]',' ',data)
    data = re.sub(r'\s+',' ',data)
    data = [lem.lemmatize(word) for word in data.split() if word not in stop]
    data = ' '.join(data)
    test_new_data.append(data)

In [19]:
test_new_data

['2019 see gadget like gaming smartphones wearable medical device lifting user experience whole new level mint india wire consumer technologyconsumer technology trend new yeartech gadgetsfoldable phonesgaming smartphoneswearable medical devicestechnology new delhi gadget become integral part life u relying form factor communicate commute work informed entertained year 2019 see gadget lifting user experience whole new level expect see smartphones foldable screen foldable phone finally moving concept stage commercial launch made organic light emitting diode oled panel higher plastic substrate allowing bent without damage u based display maker royole corp foldable phone flexpai already arrived select market samsung unnamed foldable phone expected sometime next year samsung smartphone chief executive officer j koh said make million unit lg expected display foldable phone next year meanwhile apple nokia lenovo huawei also working foldable phone reportedly esim soon smartphone need physical 

In [20]:
from sklearn .naive_bayes import MultinomialNB
from sklearn .feature_extraction.text import TfidfVectorizer,CountVectorizer

In [21]:
tfidf_train = TfidfVectorizer()
cv_train = CountVectorizer()

In [22]:
tfidf_test = TfidfVectorizer()
cv_test = CountVectorizer()

In [23]:
X_tf_train= tfidf_train.fit_transform(train_new_data).toarray()
X_cv_train = cv_train.fit_transform(train_new_data). toarray()


In [48]:
X_tf_test= tfidf_train.transform(test_new_data).toarray()
X_cv_test = cv_train.transform(test_new_data).toarray()


In [49]:
X_tf_train.shape,X_cv_train.shape

((7628, 29585), (7628, 29585))

In [50]:
X_tf_test.shape,X_cv_test.shape

((2748, 29585), (2748, 29585))

In [51]:
X_tf_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
X_tf_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.22520658, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [53]:
tfidf_train.get_feature_names()

['00',
 '000',
 '000cd',
 '000km',
 '000mah',
 '000mw',
 '001',
 '002',
 '003',
 '004',
 '005',
 '006',
 '007',
 '009',
 '01',
 '010',
 '0104',
 '0124',
 '014',
 '015',
 '0163',
 '017',
 '018',
 '01mm',
 '02',
 '020mah',
 '022',
 '0230',
 '0231',
 '024',
 '0249',
 '025',
 '026',
 '027',
 '03',
 '030',
 '0301',
 '030mah',
 '031',
 '032',
 '0329',
 '033',
 '034',
 '03539',
 '038',
 '039',
 '03am',
 '04',
 '040',
 '042',
 '0437',
 '0441',
 '045',
 '0450',
 '045mah',
 '047',
 '049',
 '05',
 '052',
 '0526hrs',
 '053',
 '055',
 '056',
 '057',
 '058',
 '059',
 '05am',
 '06',
 '060',
 '060mah',
 '064',
 '0643',
 '065',
 '065mah',
 '066',
 '067',
 '068',
 '07',
 '070',
 '0705',
 '071',
 '0713',
 '0727',
 '074',
 '0745',
 '0747',
 '075',
 '076',
 '08',
 '080',
 '0802',
 '080p',
 '081',
 '086',
 '0860',
 '087',
 '088',
 '089',
 '09',
 '090mah',
 '091',
 '092',
 '093',
 '094',
 '095',
 '096',
 '098',
 '099',
 '0gear',
 '10',
 '100',
 '1000',
 '10000pioneer',
 '1000xm3',
 '100g',
 '100gb',
 '100hz'

In [54]:
cv_train.get_feature_names()

['00',
 '000',
 '000cd',
 '000km',
 '000mah',
 '000mw',
 '001',
 '002',
 '003',
 '004',
 '005',
 '006',
 '007',
 '009',
 '01',
 '010',
 '0104',
 '0124',
 '014',
 '015',
 '0163',
 '017',
 '018',
 '01mm',
 '02',
 '020mah',
 '022',
 '0230',
 '0231',
 '024',
 '0249',
 '025',
 '026',
 '027',
 '03',
 '030',
 '0301',
 '030mah',
 '031',
 '032',
 '0329',
 '033',
 '034',
 '03539',
 '038',
 '039',
 '03am',
 '04',
 '040',
 '042',
 '0437',
 '0441',
 '045',
 '0450',
 '045mah',
 '047',
 '049',
 '05',
 '052',
 '0526hrs',
 '053',
 '055',
 '056',
 '057',
 '058',
 '059',
 '05am',
 '06',
 '060',
 '060mah',
 '064',
 '0643',
 '065',
 '065mah',
 '066',
 '067',
 '068',
 '07',
 '070',
 '0705',
 '071',
 '0713',
 '0727',
 '074',
 '0745',
 '0747',
 '075',
 '076',
 '08',
 '080',
 '0802',
 '080p',
 '081',
 '086',
 '0860',
 '087',
 '088',
 '089',
 '09',
 '090mah',
 '091',
 '092',
 '093',
 '094',
 '095',
 '096',
 '098',
 '099',
 '0gear',
 '10',
 '100',
 '1000',
 '10000pioneer',
 '1000xm3',
 '100g',
 '100gb',
 '100hz'

In [55]:
y = train_data['SECTION']


In [56]:
y.shape

(7628,)

In [57]:
X_tf_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
X_tf_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.22520658, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [59]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier


In [60]:
rn =  RandomForestClassifier(bootstrap=True)
model1 = rn.fit(X_tf_train,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [61]:
nb = MultinomialNB()
model2 = nb.fit(X_tf_train,y)

In [72]:
pred_nb_1 = model1.predict(X_tf_train)
pred_nb_2 = model2.predict(X_tf_train)


In [74]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [78]:
accuracy_score1_RF = accuracy_score(y,pred_nb_1)
accuracy_score1_RF

0.996722600943891

In [80]:
accuracy_score2_NB = accuracy_score(y,pred_nb_2)
accuracy_score2_NB

0.9686680650235973

In [81]:
test = rn.predict(X_tf_test)

In [82]:
test

array([1, 2, 1, ..., 1, 0, 1], dtype=int64)

In [83]:
test_pred = pd.DataFrame(test)

In [86]:
test_pred.to_csv('test_pred.csv')

In [88]:
test_pred.to_excel('test_pred.xlsx')